DROP TABLE IF EXISTS audit_events;
DROP FUNCTION IF EXISTS prevent_audit_event_mutation();
DROP TABLE IF EXISTS usage_rollups_hourly;
DROP TABLE IF EXISTS provider_attempts;
DROP FUNCTION IF EXISTS protect_completed_provider_attempt();
DROP TABLE IF EXISTS inference_requests;
DROP FUNCTION IF EXISTS protect_completed_inference_request();
DROP FUNCTION IF EXISTS enforce_request_route_alias();
DROP TRIGGER IF EXISTS inference_targets_protect_tenancy_update ON inference_targets;
DROP FUNCTION IF EXISTS protect_target_tenancy_update();
DROP TRIGGER IF EXISTS tenant_routes_enforce_target_tenancy ON tenant_routes;
DROP FUNCTION IF EXISTS enforce_target_tenancy();
DROP TABLE IF EXISTS tenant_routes;
DROP TABLE IF EXISTS api_keys;
DROP TABLE IF EXISTS service_accounts;
DROP TABLE IF EXISTS inference_targets;
DROP TABLE IF EXISTS models;
DROP TABLE IF EXISTS environments;
DROP TABLE IF EXISTS projects;
DROP TABLE IF EXISTS organisations;
DELETE FROM schema_migrations WHERE version = '0001_openrouter_poc';
