appname = casdoor
httpport = 19084
runmode = prod
copyrequestbody = false
driverName = sqlite
dataSourceName = file:/data/casdoor.db?cache=shared
dbName = casdoor
tableNamePrefix =
showSql = false
redisEndpoint =
defaultStorageProvider =
isCloudIntranet = false
authState = "casdoor"
verificationCodeTimeout = 10
initScore = 0
logPostOnly = true
isUsernameLowered = true
origin = http://casdoor.localhost:19084
originFrontend =
staticBaseUrl = "https://cdn.casbin.org"
isDemoMode = false
batchSize = 100
showGithubCorner = false
forceLanguage = "en"
defaultLanguage = "en"
defaultApplication = "app-built-in"
maxItemsForFlatMenu = 7
enableErrorMask = true
enableGzip = true
inactiveTimeoutMinutes = 60
ldapServerPort = 389
ldapsCertId = ""
ldapsServerPort = 636
radiusServerPort = 1812
radiusDefaultOrganization = "built-in"
radiusSecret = "local-loopback-only"
quota = {"organization": 10, "user": 100, "application": 10, "provider": 10}
logConfig = {"adapter":"console"}
initDataNewOnly = false
initDataFile = "./init_data.json"
frontendBaseDir = "../cc_0"
